version: "3.8"
services:
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Chile&2022
      MYSQL_DATABASE: bd
    ports:
      - 3307:3306
  mueblesstgo_app:
    container_name: app-web-simple
    image: poner el tuyo
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/bd
      - DB_USERNAME=root
      - DB_PASSWORD=Chile&2022
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
volumes:
  mysql-data: